export * from "./Home"
export * from "./About"
export * from "./Contacts"
export * from "./Prices"
export * from "./tours/Tours"
export * from "./Authentication/registration/Registration"
export * from "./Authentication/login/Login"
